### ISSUE TITLE
Buttons lack a visually distinct focus state

### ISSUE THREAD

**Issue by ticky** [webrecorder/webrecorder-player#49]
There’s no apparent focus state on any of the buttons in the application.

**Comment by machawk1** [comment]
The button do appear to "grow" when focused but something less subtle like a color change that is apparent while in the hover state would be useful.

**Comment by m4rk3r** [comment]
Yep, this is also addressed in the [new version](https://github.com/webrecorder/webrecorderplayer-electron/releases/tag/v1.1.1), out soon! : )

**Comment by machawk1** [comment]
@m4rk3r That info button highlight is _very_ subtle in the new version you linked. Compared to the folder rotation, it's not immediately evident that the circle-i is in focus.

**Comment by m4rk3r** [comment]
@machawk1 True, we'll tweak it some more.

**Comment by ticky** [comment]
Just fetched version 1.1.2 beta and there’s still no focus state on any buttons? There’s still definitely a _hover_ state, but keyboard navigation remains impossible.

**Comment by m4rk3r** [comment]
Hi @ticky, ah yes thanks for following up with it.. we're going to take another pass at this. You're trying to tab through the menu buttons, right?

**Comment by ticky** [comment]
Tabbing through the menu buttons and the main “open” button in the home screen, yes!

**Comment by ikreymer** [comment]
The buttons now have a tab focus in 1.6.1
