### ISSUE TITLE
Attach CMD/CTRL-O hotkey and ellipses to new File>Open command

### ISSUE THREAD

**Issue by machawk1** [webrecorder/webrecorder-player#56]
Version 1.1.1 Pre-release, the File > Open menu struck me as oddly designed:
<img width="109" alt="screen shot 2018-01-30 at 2 16 05 pm" src="https://user-images.githubusercontent.com/2514780/35586192-2d57515e-05c8-11e8-9b85-21e75ba18018.png">

compared to other Mac apps:

| TeXShop        | Chrome          | CyberDuck  |
| :-------------: |:-------------:| :-----:|
| <img width="250" alt="screen shot 2018-01-30 at 2 14 41 pm" src="https://user-images.githubusercontent.com/2514780/35586211-3c2833c4-05c8-11e8-9314-b64b70c612d4.png">     | <img width="270" alt="screen shot 2018-01-30 at 2 14 51 pm" src="https://user-images.githubusercontent.com/2514780/35586218-416fa3a8-05c8-11e8-9143-e673bb784513.png"> | <img width="282" alt="screen shot 2018-01-30 at 2 15 08 pm" src="https://user-images.githubusercontent.com/2514780/35586220-432b9080-05c8-11e8-8678-db6558717bfe.png"> |

all have the corresponding "Open" command with trailing ellipses (e.g., "Open...") and the command-O hotkey.

**Comment by ikreymer** [comment]
Fixed in 1.6.1
