### ISSUE TITLE
Way to open dev tools in the player?

### ISSUE THREAD

**Issue by vitorio** [webrecorder/webrecorder-player#59]
Hello, I'm trying to debug a WARC capture (not captured with webrecorder), and I'd like to see what Webrecorder Player is requesting that's missing from the WARC.  Is there a way to open the Dev Tools (JavaScript console, network panel, etc.) in Webrecorder Player?

**Comment by m4rk3r** [comment]
Hi @vitorio, probably your best bet is to clone the repo and build the dev version of the player. That will open up the dev tools by default.

**Comment by vitorio** [comment]
@m4rk3r Is "the dev version" this bit in the build docs?

> To start in Dev mode run:
> 
>  `$ yarn run start-dev`

**Comment by ikreymer** [comment]
Yes, that is correct. Leaving open in case we add this in a future release.

**Comment by ikreymer** [comment]
We've added support for opening the page devtools in 1.6.1
View > Toggle Page Developer Tools
