### ISSUE TITLE
Request: Clarification Data Directory

### ISSUE THREAD

**Issue by peter1000** [webrecorder/webrecorder-player#91]
Hi,

Kindly ask for some info: your other app ( webrecorder-desktop) creates *Data Directory*:
`/home/USERNAME/Documents/Webrecorder-Data` and makes a copy when importing wrac files.

Does the player also create some intermediate copies or reads directly the wrac file from the current file  location. e.g.  *attached USB drive with a .warc.gz archive.*

Thanks

**Comment by m4rk3r** [comment]
Webrecorder Player creates a cache directory in the `~/Downloads/` named `_warc_cache` to store a cache of the indexing work for quicker subsequent loads of a warc. we'll add a note about this in the readme!
